version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: jdo_user
#            POSTGRES_DB: jdo
#            POSTGRES_USER: jdo_user