alter table CaseRole drop constraint FK51EBBE6706E50D1;
alter table CaseRole drop constraint FK51EBBE67ADB9224;
alter table CaseRole drop constraint FK51EBBE6A8F708D3;
alter table CommunicationEvent drop constraint FK3612E48442528F54;
alter table CommunicationEvent drop constraint FK3612E484F72C46A;
alter table CommunicationEvent drop constraint FK3612E484DD41DC50;
alter table CommunicationEventRole drop constraint FK716BF71A91114641;
alter table CommunicationEventRole drop constraint FK716BF71A53C61999;
alter table CommunicationEventRole drop constraint FK716BF71AA5C0E5D8;
alter table CommunicationEventRole drop constraint FK716BF71A2944836E;
alter table CommunicationEventWorkEffort drop constraint FKE5602F0175559234;
alter table CommunicationEvent_CommunicationEventPurpose drop constraint FKF7C4B3FFF5AC5EF4;
alter table CommunicationEvent_CommunicationEventPurpose drop constraint FKF7C4B3FF8505B0F8;
alter table CommunicationEvent_Kase drop constraint FKBCB99923B4866508;
alter table CommunicationEvent_Kase drop constraint FKBCB9992373D6705F;
alter table ContactMechanism_PartyPostalAddress drop constraint FK343EDE49C1CC79EB;
alter table ContactMechanism_PartyPostalAddress drop constraint FK343EDE49A2496597;
alter table Facility drop constraint FK21B8D2C38DBEFFBC;
alter table FacilityContactMechanism drop constraint FK8BB433FC1C900B88;
alter table FacilityContactMechanism drop constraint FK8BB433FC3D3519CE;
alter table FacilityRole drop constraint FK1FE2ADD991114641;
alter table FacilityRole drop constraint FK1FE2ADD915B298C6;
alter table FacilityRole drop constraint FK1FE2ADD9420FD6E6;
alter table Facility_Facility drop constraint FKC7229CBFC721C75F;
alter table Facility_Facility drop constraint FKC7229CBFD8663F83;
alter table Facility_FacilityContactMechanism drop constraint FK5A285F87C72F6F0;
alter table Facility_FacilityContactMechanism drop constraint FK5A285F8D8663F83;
alter table Facility_FacilityRole drop constraint FK71F19D53C95AF22;
alter table Facility_FacilityRole drop constraint FK71F19D5D8663F83;
alter table GeographicBoundary drop constraint FK2A6717E11FD2EB99;
alter table GeographicBoundary_ContactMechanism drop constraint FKEF862FD7EF0432B1;
alter table GeographicBoundary_ContactMechanism drop constraint FKEF862FD7CA7ED0EE;
alter table GeographicBoundary_GeographicBoundary drop constraint FK725A50FF365829F8;
alter table GeographicBoundary_GeographicBoundary drop constraint FK725A50FFCA7ED0EE;
alter table GeographicBoundary_GeographicBoundary drop constraint FK725A50FF9FF432BA;
alter table Kase drop constraint FK239248461BCB34;
alter table PartyClassification drop constraint FK3608D84C750DE11B;
alter table PartyContactMechanism drop constraint FK8CDE25FF2B6B8DFB;
alter table PartyContactMechanism drop constraint FK8CDE25FF1C900B88;
alter table PartyContactMechanism drop constraint FK8CDE25FF9951DD92;
alter table PartyContactMechanismPurpose drop constraint FK383E821F18184D21;
alter table PartyContactMechanismPurpose drop constraint FK383E821FBAA3D6EF;
alter table PartyPostalAddress drop constraint FK7CE2838312414A4B;
alter table PartyPostalAddress drop constraint FK7CE28383D801EB65;
alter table PartyRelationship drop constraint FKBFACFC1EC841CA21;
alter table PartyRelationship drop constraint FKBFACFC1E6A981C48;
alter table PartyRelationship drop constraint FKBFACFC1EF5A0971F;
alter table PartyRelationship drop constraint FKBFACFC1EF7235788;
alter table PartyRelationship drop constraint FKBFACFC1E4FC66C92;
alter table PartyRole drop constraint FKCFD4C5C7D5181AB;
alter table PartyRole drop constraint FKCFD4C5C8F58E694;
drop table CaseRole;
drop table CaseRoleType;
drop table CaseStatusType;
drop table CommunicationEvent;
drop table CommunicationEventPurpose;
drop table CommunicationEventPurposeType;
drop table CommunicationEventRole;
drop table CommunicationEventRoleType;
drop table CommunicationEventStatusType;
drop table CommunicationEventWorkEffort;
drop table CommunicationEvent_CommunicationEventPurpose;
drop table CommunicationEvent_Kase;
drop table ContactMechanism;
drop table ContactMechanismPurposeType;
drop table ContactMechanism_PartyPostalAddress;
drop table Facility;
drop table FacilityContactMechanism;
drop table FacilityRole;
drop table FacilityRoleType;
drop table Facility_Facility;
drop table Facility_FacilityContactMechanism;
drop table Facility_FacilityRole;
drop table GeographicBoundary;
drop table GeographicBoundaryType;
drop table GeographicBoundary_ContactMechanism;
drop table GeographicBoundary_GeographicBoundary;
drop table Kase;
drop table Party;
drop table PartyClassification;
drop table PartyContactMechanism;
drop table PartyContactMechanismPurpose;
drop table PartyPostalAddress;
drop table PartyRelationship;
drop table PartyRole;
drop table PartyRoleType;
drop table PriorityType;
drop table StatusType;
drop table TerminationReason;
drop sequence hibernate_sequence;